### ISSUE TITLE
Allow more whitespace?

### ISSUE THREAD

**Issue by janlelis** [janlelis/relaxed.ruby.style#1]
Thinking of rules like `Extra blank line detected.`

After all, whitespace can be a good tool to make code more visual.

**Comment by asaaki** [comment]
I would vote against that.

Recently in different places people discuss this topic.

Examples:
- https://github.com/lpil/dogma/pull/166
- http://www.yegor256.com/2014/11/03/empty-line-code-smell.html

Sometimes the positions are extreme, but so is this project. :smirk: 

But seriously, until today nobody could convince (or even prove to) me, that more empty lines do improve readability, maintainability and quality.

(Somebody should go and write an article like »whitespace considered harmful« … :laughing:)

**Comment by janlelis** [comment]
Thanks for the links!

Different rule, but to point out what I mean with "visualize":

``` ruby
hello = 42
hola = 43
```

vs 

``` ruby
hello = 42
hola  = 43
```

Although the `=` is not strictly separated by one space, I find the latter more appealing to the eyes. But I wouldn't use this for:

``` ruby
long_identifier = 42
short = 43
```

**Comment by elia** [comment]
I often use some blank lines before the `private` methods section (2 or 4 usually, depending on the size of the file) and also to separate groups of methods with a leading comment/title for the section.

```rb
class A
  include B
  
  
  # Associations
  
  def foo
    # …
  end
  
  def foo2
    # …
  end
  
  
  # Scopes
  
  def bar
    # …
  end
  
  def bar2
    # …
  end
  
  
  private
  
  def baz
    # …
  end
  
  def baz2
    # …
  end
end
```
