### ISSUE TITLE
Layout/LineLength has the wrong namespace - should be Metrics

### ISSUE THREAD

**Issue by jakeonfire** [janlelis/relaxed.ruby.style#10]
getting this error with rubocop 0.74

**Comment by janlelis** [comment]
Seems to have moved to Layout namespace in newer RuboCop versions: https://github.com/janlelis/relaxed.ruby.style/pull/9#issuecomment-609052477

**Comment by jakeonfire** [comment]
ach, i have just the right (err wrong) version (0.74.0) 🤦
