### ISSUE TITLE
Redirect guide.ruby.style to rubystyle.guide

### ISSUE THREAD

**Issue by bbatsov** [janlelis/relaxed.ruby.style#7]
Hey there!

I came across your project when I wanted to register `ruby.style` to publish the community style guide there. :-) Cool idea! A bit of inspiration for tweaking the RuboCop defaults before the 1.0 release. 

I was wondering if you'd be ok to add some redirect for guide.ruby.style to rubystyle.guide? I think that would make a fun domain and doesn't really conflict with the relaxed.ruby.style concept. 

You might also consider updating the style guide references to point to the site instead of to the GitHub repo. 

P.S. Btw, I totally love your other two projects about idiosyncratic Ruby and the stdgems! Thanks for putting them together!

**Comment by janlelis** [comment]
Hey,

although I have these strong opinions about some of the (default) rules, I really like the RuboCop tool. It is not only very helpful for newcomers, it also aids more experienced users improving their coding style.

When thinking about the style guide, I sometimes miss the reasoning that led to some rule. Of course, it lies in the nature of such a project, that rules are also based on taste. But sometimes I imagine it to be helpful to have links to the discussion (or PR) which details the motivation.

For example, I just scrolled through the style guide and saw that it is recommended to use `1.0 / 2` over `1 / 2.0`. Really interesting! But also, I am curious why: Does it have performance benefits? Is it there to make it clearer to the reader that you are expecting a `Float`? Or something else etc 

Just some user feedback!

Regarding the redirect: I also don't see any problems, and I put in the redirect from http://guide.ruby.style to https://rubystyle.guide

Some time ago, I also set up some more, like http://fast.ruby.style, just didn't promote it any way ;)

Best,
Jan

PS: happy to hear that you enjoy Idiosyncratic Ruby!

**Comment by bbatsov** [comment]
> When thinking about the style guide, I sometimes miss the reasoning that led to some rule. Of course, it lies in the nature of such a project, that rules are also based on taste. But sometimes I imagine it to be helpful to have links to the discussion (or PR) which details the motivation.

Oh, I totally what you mean - trust me! The plan is for everything more or less ambiguous to have some rationale down the road. I've been short on time to fix this myself, but I'll be trying to get more people excited about working on the guide and helping with that in the months to come. 

> For example, I just scrolled through the style guide and saw that it is recommended to use 1.0 / 2 over 1 / 2.0. Really interesting! But also, I am curious why: Does it have performance benefits? Is it there to make it clearer to the reader that you are expecting a Float? Or something else etc

No performance benefits. The rationale was - make it immediately obvious that you're doing a float division and type as little as possible (that's why it doesn't suggest 1.0 / 2.0). But your point is taken. :-) And feedback is always welcome!

> Regarding the redirect: I also don't see any problems, and I put in the redirect from http://guide.ruby.style to https://rubystyle.guide

Thanks! Much appreciated!

> Some time ago, I also set up some more, like http://fast.ruby.style, just didn't promote it any way ;)

Cool! Btw, you might want to also add rails.ruby.style -> rails.rubystyle.guide and rspec.ruby.style -> rspec.rubystyle.guide while you're at it. ;-)
